@startuml modelui2
title <size:30><b>Diagramme de classes ui pour l'ajout de groupe</b></size>

package app{

  package ui{
   package addgroup{

          class AddGroupActivity extends AppCompatActivity{
              - nomGroupeEditText : EditText
              - addGroupViewModel: AddGroupViewModel
              - privateGroupSwitch: Switch

              onCreate(savedInstanceState : Bundle) : void
          }

          class AddGroupViewModel extends ViewModel{
              - isGroupCreated : MutableLiveData<Boolean>

              + isGroupCreated() : MutableLiveData<Boolean>
              - chechGroupExists(nomGroupe : String) : void
              - createGroupe(nomGroupe : String, userId: string, isPrivate: boolean): void
              + checkGroupExistsAndCreate(nomGroupe : String, userId: string, isPrivate: boolean): void
          }
      }
    }
}

@enduml