@startuml modelui7
title <size:30><b>Diagramme de classes ui de l'affichage des publications</b></size>

package app{

  package ui{

  package publication{

          class CommentaireAdapater extends RecyclerView.Adapter {
              - commentaires: List<Commentaire>

               + this: (commentaire : List<Commentaire>)

                + onCreateViewHolder(parent :@NonNull ViewGroup, viewType: int): CommentaireViewHolder
                + onBindViewHolder(holder: @NonNull final CommentaireViewHolder , position: int): void
                + getItemCount(): int

                static class CommentaireViewHolder extends RecyclerView.ViewHolder{
                     commentaireTextView : TextView
                     usernameTextView : TextView

                     + this : (itemView : View)
                }
          }


          class PublicationActivtiy extends AppCompatActivity{
                 - titreTextView: TextView
                 - miniatureImageView: ImageView
                 - likeCountTextView: TextView
                 - dislikeCountTextView: TextView
                 - commentaireEditText: EditText
                 - publication: Publication
                 - commentaireRecyclerView: RecyclerView
                 - adapter:  RecyclerView.Adapter
                 - userc : User
                 - currentUser : FirebaseAuth
                 - pseudoU : String

                 + onCreate(savedInstanceState : Bundle): void
          }

          class PublicationViewModel extends ViewModel{
              - publication: MutableLiveData<Publication>
              - commentaires: MutableLiveData<List<Commentaire>>

              + getPublication(): MutableLiveData<Publication>
              + getCommentaires(): MutableLiveData<List<Commentaire>>
              + loadPublication(publicationId : String): void
              + loadCommentaires(publicationId : String): void
              + createCommentaires(publicationId : String, content : String): void
          }
      }
   }
@enduml