@startuml modelui7
title <size:30><b>Diagramme de classes ui de l'affichage des publications</b></size>

package app{

  package ui{

  package publication{

          class CommentaireAdapater extends RecyclerView.Adapter {
              - commentaires: List<Commentaire>

               + this: (commentaire : List<Commentaire>)

                + onCreateViewHolder(parent :@NonNull ViewGroup, viewType: int): CommentaireViewHolder
                + onBindViewHolder(holder: @NonNull final CommentaireViewHolder , position: int): void
                + getItemCount(): int

                - Class CommentaireViewHolder extends RecyclerView.ViewHolder
                     commentaireTextView : TextView
                     usernameTextView : TextView

                     + this : (itemView : View)

          }

          class EmotionAdapater extends RecyclerView.Adapter {
                 - emotions: List<Emotion>

                 + this: (emotions : List<Emotion>)

                 + onCreateViewHolder(parent :@NonNull ViewGroup, viewType: int): EmotionViewHolder
                 + onBindViewHolder(holder: @NonNull final EmotionViewHolder , position: int): void
                 + getItemCount(): int

                 static class EmotionViewHolder extends RecyclerView.ViewHolder
                         emotionIV : ImageView
                         usernameTV : TextView

                       + this : (itemView : View)

          }

          class EmotionMainProfileAdapater extends RecyclerView.Adapter {
                 - emotions: List<Emotion>

                 + this: (emotions : List<Emotion>)

                 + onCreateViewHolder(parent :@NonNull ViewGroup, viewType: int): EmotionMainProfileViewHolder
                 + onBindViewHolder(holder: @NonNull final EmotionMainProfileViewHolder , position: int): void
                 + groupName(holder : EmotionMainProfileViewHolder, groupId : String): void
                 + getItemCount(): int

                 - Class EmotionMainProfileViewHolder extends RecyclerView.ViewHolder
                         emotion_user : ImageView
                         username_emotion : TextView
                         publication_name : TextView
                         group_name : TextView

                       + this : (itemView : View)


          }

          class PublicationActivtiy extends AppCompatActivity{
                 - titreTextView: TextView
                 - miniatureImageView: ImageView
                 - likeCountTextView: TextView
                 - dislikeCountTextView: TextView
                 - commentaireEditText: EditText
                 - publication: Publication
                 - commentaireRecyclerView: RecyclerView
                 - emotionRecyclerView: RecyclerView
                 - adapter:  RecyclerView.Adapter
                 - userc : User
                 - currentUser : FirebaseAuth
                 - pseudoU : String
                 - veryHappyCountTV : TextView
                 - happyCountTV : TextView
                 - sadCountTV : TextView
                 - verySadCountTV : TextView

                 + onCreate(savedInstanceState : Bundle): void
          }

          class PublicationViewModel extends ViewModel{
              - publicationLiveData: MutableLiveData<Publication>
              - commentaires: MutableLiveData<List<Commentaire>>
              - emotionsLiveData : MutableLiveData<List<Emotion>>
              - authorUserLiveData: MutableLiveData<User>
              - currentUserLiveData: MutableLiveData<User>

              + getPublication(): MutableLiveData<Publication>
              + getCommentaires(): MutableLiveData<List<Commentaire>>
              + getEmotionsLiveData() : MutableLiveData<List<Emotion>>
              + getAuthorUserLiveData(): MutableLiveData<User>
              + loadPublication(publicationId : String): void
              + loadEmotions(publicationId : String): void
              + loadAuthorUser(publication : Publication): void
              + loadCurrentUser(userId : String): void
              + removeOldEmotion(userId : String, publicationId : String, newEmotionId : String): void
              + addEmotion(emotionName: String): void
          }


@enduml