@startuml modelui8
title <size:30><b>Diagramme de classes ui de la page d'inscription</b></size>

package app{

  package ui{

        package register{

                class RegisterActivity extends AppCompatActivity implements View.OnClickListener{
                        - TAG: String
                        - uPrenom: EditText
                        - uNom:  EditText
                        - uPseudo:  EditText
                        - uEmail: EditText
                        - uMdp: EditText
                        - mAuth: FirebaseAuth
                        - prgB: ProgressBar
                        - btn_groupe: RadioGroup

                        + onCreate(savedInstanceState : Bundle): void
                        + onClick(v : View): void
                        - registerUser(): void
                }
            }
        }
  }
@enduml