@startuml modelui6
title <size:30><b>Diagramme de classes ui de la page principale</b></size>

package app{

  package ui{

  package main{

          class MainActivity extends AppCompatActivity{
              - publicationRecyclerView: RecyclerView
              - adapter: RecyclerView.Adapter
              - user : FirebaseAuth

              + onCreate(savedInstanceState : Bundle): void
          }

          class MainViewModel extends ViewModel{
               - publications : MutableLiveData<List<Publication>>
               - groupeMutableLiveData : MutableLiveData<Groupe>

               + getPublications() : MutableLiveData<List<Publication>>
               + getGroupeMutableLiveData() : MutableLiveData<Groupe>
               + getGroupe(uid : String) : void
               + loadPublicationsTitre() : void
               + loadPublicationsDate(): void
               + loadPublicationsLike(): void
          }

          class PublicationAdapter extends RecyclerView.Adapter{
              - publications : List<Publication>

              + this : (publications : List<Publication>)

              + onCreateViewHolder(parent :@NonNull ViewGroup, viewType: int): PublicationViewHolder
              + onBindViewHolder(holder: @NonNull final PublicationViewHolder , position: int): void
              + getItemCount(): int

              static class PublicationViewHolder extends RecyclerView.ViewHolder
                     titreTextView: TextView
                     miniatureImageView: ImageView
                     likeCountTextView: TextView
                     dislikeCountTextView: TextView
                     likeButton: LinearLayout
                     dislikeButton: LinearLayout
                     delete_btn : ImageView

                     + this: (v: View)
            }
        }
  }
}
@enduml