@startuml modelui
title <size:30><b>Diagramme de classes ui de la recherche</b></size>

package app{

  package ui{

    package search{

        class SearchActivity extends AppCompatActivity {
            - recherche: EditText
            - liste_groupe: RecyclerView
            - adapter: RecyclerView.Adapter
            - searchViewModel: SearchViewModel

            + onCreate(savedInstanceState : Bundle): void
        }

         class SearchActivityPublication extends AppCompatActivity {
                    - recherche: EditText
                    - liste_pub: RecyclerView
                    - adapter: RecyclerView.Adapter
                    - searchViewModel: SearchViewModel

                    + onCreate(savedInstanceState : Bundle): void
                }

        class SearchViewModel{
              - publications: MutableLiveData<List<Publication>>
              - groupes: MutableLiveData<List<Groupe>>
              + getPublications(): MutableLiveData<List<Publication>>
              + getGroupes(): MutableLiveData<List<Groupe>>
              # searchPublicationsTitle(titre: String, groupeId : String) : void
              # searchGroup(groupe : String): void
        }
       }
    }
 }
@enduml