@startuml modelui4
title <size:30><b>Diagramme de classes ui liste de groupes</b></size>

package app{

  package ui{
        package listgroup{

                class GroupeAdapter extends RecyclerView{
                    - groupeList: List<Group>

                    + this : (groupeList: List<Groupe>)


                    + onCreateViewHolder(parent : ViewGroup, viewType : int): GroupeViewHolder
                    + onBindViewHolder(holder : GroupeViewHolder, position: int): void
                    + getItemCount() : int

                    static class GroupeViewHolder extends RecyclerView.ViewHolder
                         groupNameTextView : TextView

                        + this : (itemView : View)

                }

                class ListGroupActivity extends AppCompatActivity {
                    - groupeRecyclerView : RecyclerView
                    - adapter : RecyclerView.Adapter

                    # onCreate(savedInstanceState : Bundle): void
                }

                class ListGroupViewModel extends ViewModel{
                    - groupesLiveData : MutableLiveData<List<Groupe>>

                    + getGroupesLiveData() : MutableLiveData<List<Groupe>>
                    + loadGroupes() : void
                }
            }
    }
}

@enduml